package githubapp

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	ArtifactWorkflowPath = ".github/workflows/uigraph-artifact.yml"
	SyncWorkflowPath     = ".github/workflows/uigraph-sync.yml"
)

func Branch(onboardingID string) string {
	return "uigraph/onboarding/" + onboardingID
}

func Seed(orgName, repoName, repoURL, teamName string) ([]byte, error) {
	type named struct {
		Name string `yaml:"name"`
	}
	type repository struct {
		Provider string `yaml:"provider"`
		URL      string `yaml:"url"`
	}
	value := struct {
		Version int   `yaml:"version"`
		Project named `yaml:"project"`
		Service struct {
			Name        string     `yaml:"name"`
			Category    string     `yaml:"category"`
			Description string     `yaml:"description"`
			Repository  repository `yaml:"repository"`
			Ownership   struct {
				Team string `yaml:"team"`
			} `yaml:"ownership"`
		} `yaml:"service"`
	}{}
	value.Version = 1
	value.Project.Name = orgName
	value.Service.Name = HumanizeRepositoryName(repoName)
	value.Service.Category = "service"
	value.Service.Description = fmt.Sprintf("%s service", value.Service.Name)
	value.Service.Repository.Provider = "github"
	value.Service.Repository.URL = repoURL
	value.Service.Ownership.Team = teamName
	return yaml.Marshal(value)
}

func HumanizeRepositoryName(name string) string {
	name = strings.TrimSpace(strings.NewReplacer("-", " ", "_", " ", ".", " ").Replace(name))
	parts := strings.Fields(name)
	for index, part := range parts {
		if part == "api" {
			parts[index] = "API"
			continue
		}
		parts[index] = strings.ToUpper(part[:1]) + part[1:]
	}
	if len(parts) == 0 {
		return "Service"
	}
	return strings.Join(parts, " ")
}

func ArtifactWorkflow(defaultBranch string) []byte {
	return []byte(fmt.Sprintf(`name: UiGraph Artifact
on:
  push:
    branches:
      - %[1]s
      - "uigraph/onboarding/**"
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: uigraph-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  artifact:
    if: "!contains(github.event.commits.*.author.name, 'uigraph-artifact[bot]')"
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.push.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Generate repository artifacts
        env:
          AI_PROVIDER_API_KEY: ${{ secrets.AI_PROVIDER_API_KEY }}
          AI_PROVIDER_MODEL: ${{ secrets.AI_PROVIDER_MODEL || vars.AI_PROVIDER_MODEL }}
          AI_PROVIDER_API_URL: ${{ secrets.AI_PROVIDER_API_URL || vars.AI_PROVIDER_API_URL }}
          AI_PROVIDER_NPM: ${{ secrets.AI_PROVIDER_NPM || vars.AI_PROVIDER_NPM }}
        run: npx --yes @uigraph/agents@experimental artifacts init --seeded
      - name: Restrict generated changes
        run: |
          unexpected=$(git status --porcelain | awk '{print $2}' | grep -Ev '^(.uigraph.yaml|.uigraph/)' || true)
          test -z "$unexpected" || { printf 'Generation changed unsupported paths:\n%%s\n' "$unexpected"; exit 1; }
      - name: Push generated artifacts
        id: push
        if: startsWith(github.ref_name, 'uigraph/onboarding/')
        run: |
          git config user.name "uigraph-artifact[bot]"
          git config user.email "uigraph-artifact[bot]@users.noreply.github.com"
          git add .uigraph.yaml
          if [ -d .uigraph ]; then
            git add .uigraph
          fi
          if git diff --cached --quiet; then
            echo "Generation produced no changes"
          else
            git commit -m "chore(uigraph): generate repository artifacts"
            git push origin "HEAD:${GITHUB_REF_NAME}"
            echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          fi
      - name: Open artifact pull request
        if: github.ref_name == '%[1]s'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config user.name "uigraph-artifact[bot]"
          git config user.email "uigraph-artifact[bot]@users.noreply.github.com"
          git add .uigraph.yaml
          if [ -d .uigraph ]; then
            git add .uigraph
          fi
          if git diff --cached --quiet; then
            echo "Generation produced no changes"
          else
            branch="uigraph/artifacts/${GITHUB_RUN_ID}"
            git checkout -b "$branch"
            git commit -m "chore(uigraph): generate repository artifacts"
            git push origin "$branch"
            gh pr create --base "%[1]s" --head "$branch" --title "UiGraph: update repository artifacts" --body "Generated by the UiGraph artifact workflow."
          fi
  run-sync:
    needs: artifact
    if: needs.artifact.outputs.sha != ''
    uses: ./.github/workflows/uigraph-sync.yml
    with:
      ref: ${{ needs.artifact.outputs.sha }}
    secrets: inherit
`, defaultBranch))
}

func SyncWorkflow(defaultBranch string) []byte {
	return []byte(fmt.Sprintf(`name: UiGraph Sync
on:
  push:
    branches:
      - %[1]s
      - "uigraph/onboarding/**"
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
permissions:
  contents: read
concurrency:
  group: uigraph-sync-${{ github.ref }}
  cancel-in-progress: false
jobs:
  sync:
    if: inputs.ref != '' || contains(github.event.commits.*.author.name, 'uigraph-artifact[bot]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout called ref
        if: inputs.ref != ''
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Checkout pushed ref
        if: inputs.ref == ''
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go install github.com/uigraph-oss/uigraph-cli@main
      - name: Sync
        env:
          UIGRAPH_TOKEN: ${{ secrets.UIGRAPH_TOKEN }}
          UIGRAPH_GATEWAY_URL: ${{ vars.UIGRAPH_GATEWAY_URL || secrets.UIGRAPH_GATEWAY_URL }}
        run: uigraph-cli sync
`, defaultBranch))
}
