package githubapp

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	CreatePullRequestVersion = "v7"
)

func SetupBranch(onboardingID string) string {
	return "uigraph/setup/" + onboardingID
}

func ArtifactsBranch(onboardingID string) string {
	return "uigraph/generated/" + onboardingID
}

func Seed(orgName, repoName, repoURL, teamName string) ([]byte, error) {
	type named struct {
		Name string `yaml:"name"`
	}
	type repository struct {
		Provider string `yaml:"provider"`
		URL      string `yaml:"url"`
	}
	value := struct {
		Version int   `yaml:"version"`
		Project named `yaml:"project"`
		Service struct {
			Name        string     `yaml:"name"`
			Category    string     `yaml:"category"`
			Description string     `yaml:"description"`
			Repository  repository `yaml:"repository"`
			Ownership   struct {
				Team string `yaml:"team"`
			} `yaml:"ownership"`
		} `yaml:"service"`
	}{}
	value.Version = 1
	value.Project.Name = orgName
	value.Service.Name = HumanizeRepositoryName(repoName)
	value.Service.Category = "service"
	value.Service.Description = fmt.Sprintf("%s service", value.Service.Name)
	value.Service.Repository.Provider = "github"
	value.Service.Repository.URL = repoURL
	value.Service.Ownership.Team = teamName
	return yaml.Marshal(value)
}

func HumanizeRepositoryName(name string) string {
	name = strings.TrimSpace(strings.NewReplacer("-", " ", "_", " ", ".", " ").Replace(name))
	parts := strings.Fields(name)
	for index, part := range parts {
		if part == "api" {
			parts[index] = "API"
			continue
		}
		parts[index] = strings.ToUpper(part[:1]) + part[1:]
	}
	if len(parts) == 0 {
		return "Service"
	}
	return strings.Join(parts, " ")
}

func GenerateWorkflow(onboardingID, defaultBranch string) []byte {
	return []byte(fmt.Sprintf(`name: UiGraph Generate
on:
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: uigraph-generate-${{ github.repository }}
  cancel-in-progress: false
jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      AI_PROVIDER_API_KEY: ${{ secrets.AI_PROVIDER_API_KEY }}
      AI_PROVIDER_MODEL: ${{ vars.AI_PROVIDER_MODEL }}
      AI_PROVIDER_API_URL: ${{ vars.AI_PROVIDER_API_URL }}
      AI_PROVIDER_NPM: ${{ vars.AI_PROVIDER_NPM }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: %s
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npx --yes @uigraph/agents@experimental artifacts init --seeded
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go install github.com/uigraph-oss/uigraph-cli@main
      - run: uigraph-cli validate
      - name: Restrict generated changes
        run: |
          unexpected=$(git status --porcelain | awk '{print $2}' | grep -Ev '^(.uigraph.yaml|.uigraph/)' || true)
          test -z "$unexpected" || { printf 'Generation changed unsupported paths:\n%%s\n' "$unexpected"; exit 1; }
      - uses: peter-evans/create-pull-request@%s
        with:
          token: ${{ github.token }}
          branch: %s
          base: %s
          title: "UiGraph: generate repository artifacts"
          commit-message: "chore(uigraph): generate repository artifacts"
          body: "Generated by the UiGraph onboarding workflow."
          add-paths: |
            .uigraph.yaml
            .uigraph/**
`, defaultBranch, CreatePullRequestVersion, ArtifactsBranch(onboardingID), defaultBranch))
}

func SyncWorkflow() []byte {
	return []byte(`name: UiGraph Sync
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: uigraph-sync-${{ github.repository }}
  cancel-in-progress: false
jobs:
  sync:
    if: github.event_name == 'workflow_dispatch' || github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    env:
      UIGRAPH_TOKEN: ${{ secrets.UIGRAPH_ONBOARDING_TOKEN }}
      UIGRAPH_GATEWAY_URL: ${{ vars.UIGRAPH_GATEWAY_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Check generated artifacts
        id: artifacts
        run: |
          if [ -d .uigraph ]; then echo "exists=true" >> "$GITHUB_OUTPUT"; else echo "exists=false" >> "$GITHUB_OUTPUT"; fi
      - if: steps.artifacts.outputs.exists == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - if: steps.artifacts.outputs.exists == 'true'
        run: go install github.com/uigraph-oss/uigraph-cli@latest
      - if: steps.artifacts.outputs.exists == 'true'
        run: uigraph-cli sync
`)
}
